# Generated by Django 2.2 on 2023-01-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=50, verbose_name='Вид животного')),
                ('name', models.CharField(max_length=50, verbose_name='Класс')),
                ('image', models.ImageField(upload_to='%Y/%m/%d/', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Краткое описание животного')),
                ('date_of_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания статьи')),
            ],
        ),
    ]
