# Generated by Django 3.2 on 2023-02-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zoo',
            options={'verbose_name': 'Животное', 'verbose_name_plural': 'Животные'},
        ),
    ]
