# Generated by Django 3.2 on 2023-02-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_alter_zoo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoo',
            name='image',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
